let svg = d3.select("#chart-area").append("svg")
  .attr("width", 500)
  .attr("height", 500)
  .attr("id", "canvas")

let circle2 = svg.append("circle")
  .attr("cx", 100)
  .attr("cy", 100)
  .attr("r", 400)
  .attr("fill", "lightgrey")
    
let circle = svg.append("circle")
  .attr("cx", 250)
  .attr("cy", 250)
  .attr("r", 100)
  .attr("fill", "red")
  .attr("stroke", "darkred")
  .attr("stroke-width", 5)

let rectangle = svg.append("rect")
  .attr("width", 400)
  .attr("height", 10)
  .attr("x", 100)
  .attr("y", 400)
  .attr("fill", "hotpink")
  
let rectange = svg.append("rect")
  .attr("width", 400)
  .attr("height", 6)
  .attr("x", 0)
  .attr("y", 415)
  .attr("fill", "turquoise")
